# Generated by Django 3.1.7 on 2021-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ends_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='starts_on',
            field=models.DateField(),
        ),
    ]
