# Generated by Django 3.1.7 on 2021-03-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210312_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseevaluations',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodules',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
