# Generated by Django 3.1.7 on 2021-03-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210312_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseevaluations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coursemodules',
            name='created_by',
        ),
    ]
