# Generated by Django 3.1.7 on 2021-03-11 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user-auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 11, 19, 37, 1, 732490, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
